apiVersion: v1
kind: Service
metadata:
  labels:
    name: hello-nodeport
  name: hello-nodeport
spec:
  ports:
  - name: 8080-tcp
    nodePort: 32564
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-openshift
  sessionAffinity: None
  type: NodePort