kind: Pod
apiVersion: v1
metadata:
  name: hello-openshift2
  creationTimestamp:
  labels:
    name: hello-openshift
    app: hello-openshift
spec:
  containers:
  - name: hello-openshift
    image: openshift/hello-openshift
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    volumeMounts:
    - name: tmp
      mountPath: "/tmp"
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities: {}
      privileged: false
  volumes:
  - name: tmp
    emptyDir: {}
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  serviceAccount: ''
status: {}